name: sora
base-image: ghcr.io/ublue-os/silverblue-main

fedora-version: 39

description: Personal Linux OS based on swayfx and fedora silverblue

scripts:
    # - example.sh

rpm:
  repos:
    - https://copr.fedorainfracloud.org/coprs/swayfx/swayfx/repo/fedora-%FEDORA_VERSION%/swayfx-swayfx-fedora-%FEDORA_VERSION%.repo
    - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%FEDORA_VERSION%/atim-starship-fedora-%FEDORA_VERSION%.repo
    - https://copr.fedorainfracloud.org/coprs/tokariew/glow/repo/fedora-%FEDORA_VERSION%/tokariew-glow-fedora-%FEDORA_VERSION%.repo
    - https://copr.fedorainfracloud.org/coprs/tofik/nwg-shell/repo/fedora-%FEDORA_VERSION%/tofik-nwg-shell-fedora-%FEDORA_VERSION%.repo
    - https://copr.fedorainfracloud.org/coprs/peterwu/rendezvous/repo/fedora-%FEDORA_VERSION%/peterwu-rendezvous-fedora-%FEDORA_VERSION%.repo
    - https://copr.fedorainfracloud.org/coprs/atim/himalaya/repo/fedora-%FEDORA_VERSION%/atim-himalaya-fedora-%FEDORA_VERSION%.repo 
    - https://copr.fedorainfracloud.org/coprs/mecattaf/iwgtk/repo/fedora-%FEDORA_VERSION%/mecattaf-iwgtk-fedora-%FEDORA_VERSION%.repo
    - https://copr.fedorainfracloud.org/coprs/mecattaf/catppuccin-theme/repo/fedora-%FEDORA_VERSION%/mecattaf-catppuccin-theme-fedora-%FEDORA_VERSION%.repo
    - https://copr.fedorainfracloud.org/coprs/mecattaf/chezmoi/repo/fedora-%FEDORA_VERSION%/mecattaf-chezmoi-fedora-%FEDORA_VERSION%.repo
    - https://copr.fedorainfracloud.org/coprs/mecattaf/marp-cli/repo/fedora-%FEDORA_VERSION%/mecattaf-marp-cli-fedora-%FEDORA_VERSION%.repo
    - https://pkgs.tailscale.com/stable/fedora/tailscale.repo

  remove:
    - firefox
    - firefox-langpacks
    - virtualbox-guest-additions
    - toolbox
    - nvtop

  install:
    - python3-pip
    - libadwaita
    - swayfx
    - starship
    - mako
    - fish
    - distrobox
    - lxpolkit
    - polkit-gnome
    - alacritty
    - kitty
    - kitty-terminfo
    - clipman
    - gammastep
    - light
    - grim
    - mako
    - remmina
    - slurp
    - wayvnc
    - waybar
    - remmina
    - wl-clipboard
    - neovim
    - ripgrep
    - pandoc
    - kanshi
    - swappy
    - wshowkeys
    - fzf
    - azote
    - nwg-look
    - zathura
    - zathura-pdf-poppler
    - udiskie
    - network-manager-applet
    - xdg-desktop-portal
    - xdg-desktop-portal-wlr
    - xdg-user-dirs
    - gnome-keyring
    - stow
    - gcc
    - g++
    - nautilus
    - blueman
    - bluez-tools
    - iwd
    - iwgtk
    - pavucontrol
    - mpd
    - mpc
    - mpdris2
    - ncmpcpp
    - sox
    - glow
    - wf-recorder
    - yt-dlp
    - aria2
    - bibata-cursor-themes
    - tailscale
    - catppuccin-theme
    - himalaya
    - chezmoi
    - marp-cli

    # drivers
    - mesa-dri-drivers
    - mesa-vulkan-drivers
    - vulkan-validation-layers

    # qt stuff
    - qt5-qtgraphicaleffects
    - qt5-qtquickcontrols
    - qt5-qtquickcontrols2
    - qt5-qtwayland
    - qt6-qtwayland
    - qt5ct
    - qt6ct
    - qt5-qtsvg

type: fonts
fonts:
  nerd-fonts:
    - Iosevka
    - JetBrainsMono
    - NerdFontsSymbolsOnly

firstboot:
  yafti: false
  flatpaks:
    # core
    - com.google.Chrome
    - org.videolan.VLC

    # investigate, flatpak is not useful
    - io.github.realmazharhussain.GdmSettings

    # gaming
    - org.desmume.DeSmuME
    - io.mgba.mGBA
    - org.ppsspp.PPSSPP

    # GUI programs
    - net.mkiol.SpeechNote
    - io.bassi.Amberol
    - com.hunterwittenborn.Celeste
    
    # if program is not captured by obs:
    # flatpak override --share=network <APP ID>
    - com.obsproject.Studio
    - com.obsproject.Studio.Plugin.OBSVkCapture
    - org.freedesktop.Platform.VulkanLayer.OBSVkCapture
    - org.freedesktop.Platform.GStreamer.gstreamer-vaapi
