name: sora
base-image: ghcr.io/ublue-os/silverblue-main

fedora-version: 39

description: Personal Linux OS based on swayfx and fedora silverblue

scripts:
    # - example.sh

rpm:
  repos:
    - https://copr.fedorainfracloud.org/coprs/swayfx/swayfx/repo/fedora-%FEDORA_VERSION%/swayfx-swayfx-fedora-%FEDORA_VERSION%.repo
    - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%FEDORA_VERSION%/atim-starship-fedora-%FEDORA_VERSION%.repo
    - https://copr.fedorainfracloud.org/coprs/tokariew/glow/repo/fedora-%FEDORA_VERSION%/tokariew-glow-fedora-%FEDORA_VERSION%.repo
    - https://copr.fedorainfracloud.org/coprs/tofik/nwg-shell/repo/fedora-%FEDORA_VERSION%/tofik-nwg-shell-fedora-%FEDORA_VERSION%.repo

  remove:
    - firefox
    - firefox-langpacks
    - virtualbox-guest-additions
    - toolbox
    - nvtop
    # - THOMAS remove unwanted packages from here

  install:
    - python3-pip
    - libadwaita
    - swayfx
    - starship
    - mako
    - fish
    - distrobox
    - lxpolkit
    - polkit-gnome
    - alacritty
    - clipman
    - gammastep
    - light
    - grim
    - mako
    - remmina
    - slurp
    - wayvnc
    - waybar
    - remmina
    - wl-clipboard
    - neovim
    - kanshi
    - swappy
    - fzf
    - azote
    - nwg-look
    - udiskie
    - network-manager-applet
    - xdg-desktop-portal
    - xdg-desktop-portal-wlr
    - xdg-user-dirs
    - gnome-keyring
    - gh
    - gcc
    - blueman
    - bluez-tools
    - glow

firstboot:
  yafti: true
  flatpaks:
    - com.google.Chrome
    - org.desmume.DeSmuME
    - io.mgba.mGBA
    - io.github.realmazharhussain.GdmSettings
    - org.videolan.VLC
    - org.ppsspp.PPSSPP
    - com.obsproject.Studio
    - com.obsproject.Studio.Plugin.OBSVkCapture
    # if program is not captured by obs:
    # flatpak override --share=network <APP ID>
    - org.freedesktop.Platform.VulkanLayer.OBSVkCapture
    - org.freedesktop.Platform.GStreamer.gstreamer-vaapi
    - net.mkiol.SpeechNote
