name: sericeafx

base-image: quay.io/fedora-ostree-desktops/sericea

fedora-version: 38

description: Lightweight immutable desktop based on ublue-os and fedora sericea

scripts:
    # - example.sh

rpm:
  repos:
    - https://copr.fedorainfracloud.org/coprs/swayfx/swayfx/repo/fedora-%FEDORA_VERSION%/swayfx-swayfx-fedora-%FEDORA_VERSION%.repo

  remove:
    - firefox
    - firefox-langpacks
    - sway
    - sway-config-fedora
    - rofi-wayland
    - rofi-themes
    - virtualbox-guest-additions
    - dunst
    - toolbox
    - foot
    - thunar
    # -sway-systemd
    # - THOMAS remove unwanted packages from here

  install:
    - python3-pip
    - libadwaita
    - swayfx
    - mako
    - fish
    - distrobox
    - lxpolkit
    - alacritty
    - clipman
    - gammastep
    - light
    - grim
    - mako
    - remmina
    - slurp
    - wayvnc
    - wl-clipboard
    - zathura
    - zathura-pdf-poppler
    - kanshi
    - swappy
    - fzf
    - azote
    - bluez-tools
    #- wev

firstboot:
  yafti: true
  flatpaks:
    - com.google.Chrome
    - org.gnome.Nautilus
    - org.desmume.DeSmuME
    - io.mgba.mGBA
    - org.videolan.VLC
