name: SericeaFX

base-image: quay.io/fedora-ostree-desktops/sericea

fedora-version: 38

description: Lightweight immutable desktop based on ublue-os and fedora sericea

scripts:
    # - example.sh

rpm:
  repos:
    - https://copr.fedorainfracloud.org/coprs/swayfx/swayfx/repo/fedora-%FEDORA_VERSION%/swayfx-swayfx-fedora-%FEDORA_VERSION%.repo

  install:
    - python3-pip
    - libadwaita
    - swayfx
    # - THOMAS this is where all the packages go  

  remove:
    - firefox
    - firefox-langpacks
    - sway
    # - THOMAS remove unwanted packages from here

firstboot:
  yafti: true
  flatpaks:
    - com.google.Chrome
    - org.desmume.DeSmuME
    - io.mgba.mGBA
    - org.videolan.VLC
