name: sericeafx

base-image: ghcr.io/ublue-os/silverblue-main

fedora-version: 38

description: Lightweight immutable desktop based on ublue-os and fedora silverblue

scripts:
    # - example.sh

rpm:
  repos:
    - https://copr.fedorainfracloud.org/coprs/swayfx/swayfx/repo/fedora-%FEDORA_VERSION%/swayfx-swayfx-fedora-%FEDORA_VERSION%.repo
    - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%FEDORA_VERSION%/atim-starship-fedora-%FEDORA_VERSION%.repo
    - https://copr.fedorainfracloud.org/coprs/tokariew/glow/repo/fedora-%FEDORA_VERSION%/tokariew-glow-fedora-%FEDORA_VERSION%.repo

  remove:
    - firefox
    - firefox-langpacks
    - virtualbox-guest-additions
    - toolbox
    # -sway-systemd
    # - THOMAS remove unwanted packages from here

  install:
    - python3-pip
    - libadwaita
    - swayfx
    - starship
    - mako
    - fish
    - distrobox
    - lxpolkit
    - alacritty
    - clipman
    - gammastep
    - light
    - grim
    - mako
    - remmina
    - slurp
    - wayvnc
    - waybar
    - wl-clipboard
    - neovim
    - kanshi
    - swappy
    - fzf
    - azote
    - bluez-tools
    - glow

firstboot:
  yafti: true
  flatpaks:
    - com.google.Chrome
    - org.desmume.DeSmuME
    - io.mgba.mGBA
    - org.videolan.VLC
